on:
  push:
    branches:
      - master
jobs:
- name: SQS trigger
  uses: ItsKarma/aws-cli@v1.70.0
  with:
    args: sqs send-message --queue-url ${{ secrets.SQS_QUEUE_URL }} --message-body "file://${GITHUB_EVENT_PATH}"
  env:
    AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
    AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    AWS_DEFAULT_REGION: ${{ secrets.AWS_REGION }}
